export const CARRITO_DE_COMPRAS = 'LISTADO_COMPRAS'
export const CARRITO_DE_COMPRAS_EXITO = 'LISTADO_COMPRAS_EXITO'
export const OBTENER_COMPRA_ELIMINAR = 'OBTENER_COMPRA_ELIMINAR'
export const OBTENER_COMPRA_ELIMINAR_EXITO = 'OBTENER_COMPRA_ELIMINAR_EXITO'