export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"


export const CART_LOAD = 'CART_LOAD'
export const CART_LOAD_FINISHED = 'CART_LOAD_FINISHED'
export const CART_LOAD_ERROR = 'CART_LOAD_ERROR'
export const DELETE_FLIGHT_RESERVATION = 'DELETE_FLIGHT_RESERVATION'
export const DELETE_FLIGHT_RESERVATION_FINISHED = 'DELETE_FLIGHT_RESERVATION_FINISHED'
export const DELETE_ALL_CART = "DELETE_ALL_CART"
export const DELETE_ALL_CART_FINISHED = 'DELETE_ALL_CART_FINISHED'
export const BUY_CART = 'BUY_CART'
export const BUY_CART_FINISHED = 'BUY_CART_FINISHED'
export const BUY_CART_ERROR = 'BUY_CART_ERROR'

export const FLIGHT_SEARCH_LOAD = 'FLIGHT_SEARCH_LOAD'
export const FLIGHT_SEARCH_LOAD_FINISHED = 'FLIGHT_SEARCH_LOAD_FINISHED'
export const FLIGHT_SEARCH_LOAD_ERROR = 'FLIGHT_SEARCH_LOAD_FINISHED'
export const SEARCH_BY_DATE = 'SEARCH_BY_DATE'
export const SEARCH_BY_DATE_FINISHED = 'SEARCH_BY_DATE_FINISHED'
export const SEARCH_BY_DATE_ERROR = 'SEARCH_BY_DATE_ERROR'
export const LOAD_SEAT = 'LOAD_SEAT'
export const LOAD_SEAT_FINISHED = 'LOAD_SEAT_FINISHED'
export const LOAD_SEAT_ERROR = 'LOAD_SEAT_ERROR'
export const LOAD_FILTERED_WINDOW_SEATS = 'LOAD_FILTERED_WINDOW_SEATS'
export const LOAD_FILTERED_WINDOW_SEATS_FINISHED = 'LOAD_FILTERED_WINDOW_SEATS_FINISHED'
export const LOAD_FILTERED_WINDOW_SEATS_ERROR = 'LOAD_FILTERED_WINDOW_SEATS_ERROR'