export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"


export const CART_LOAD = 'CART_LOAD'
export const CART_LOAD_FINISHED = 'CART_LOAD_FINISHED'
export const CART_LOAD_ERROR = 'CART_LOAD_ERROR'
export const DELETE_FLIGHT_RESERVATION = 'DELETE_FLIGHT_RESERVATION'
export const DELETE_FLIGHT_RESERVATION_FINISHED = 'DELETE_FLIGHT_RESERVATION_FINISHED'
export const DELETE_FLIGHT_RESERVATION_ERROR = 'DELETE_FLIGHT_RESERVATION_ERROR'
export const DELETE_ALL_CART = "DELETE_ALL_CART"
export const DELETE_ALL_CART_FINISHED = 'DELETE_ALL_CART_FINISHED'
export const BUY_CART = 'BUY_CART'
export const BUY_CART_FINISHED = 'BUY_CART_FINISHED'
export const BUY_CART_ERROR = 'BUY_CART_ERROR'
